### PR TITLE
Upstream update

### PR DESCRIPTION
**Pull request by BlackIkeEagle**
Added some updates to make vim-qt work with the newer vim upstream versions.

The display_errors thing is not entirely fixed, It compiles, but the errors are not displayed.

### CODE REVIEW

**Comment by equalsraf** [comment]
Cheers @BlackIkeEagle, thanks a million for this.

I'm keeping track of some of your patches here https://bitbucket.org/equalsraf/vim-qt/branch/merge-upstream

> The display_errors thing is not entirely fixed, It compiles, but the errors are not displayed.

What errors are you testing with? do_dialog itself seems to be working here.

**Comment by BlackIkeEagle** [comment]
@equalsraf I interpreted it wrong, I'm using vdebug as a plugin and in cli vim or gtk vim the print's in the python scripts directly show in vim, with vim-qt it shows when the script ends, so no flushes in between.

**Comment by BlackIkeEagle** [comment]
there were some major changes in 7.4.2063 related to eval.c

**Comment by jeaye** [comment]
Any update on this?

**Comment by equalsraf** [comment]
> Any update on this?

Clearly I've been neglecting vim-qt for way too long. Its time to find a new maintainer for this project.

@BlackIkeEagle sorry for the long hiatus, I've been AFK for the past months and this ended up being ignored even further. Would you been interested in keep working on this? I'd be happy to add the necessary redirects and poke the right people to check your repo instead of mine.

**Comment by jeaye** [comment]
Given that people are already coming here, how do you feel about adding @BlackIkeEagle as a contributer and merging this PR?

**Comment by BlackIkeEagle** [comment]
@equalsraf Don't be sorry, I'm also busy doing other stuff :)

I'll update the PR to the latest Vim before we can merge this

**Comment by BlackIkeEagle** [comment]
@equalsraf Another question, how much is bitbucket diverted from github?

**Comment by equalsraf** [comment]
```
$ git diff bitbucket/master github/master
$
```
Nothing in master :D

**Comment by BlackIkeEagle** [comment]
By popular request, latest update to v8.0.0402

**Comment by jeaye** [comment]
Thanks, @equalsraf and @BlackIkeEagle!

**Pull request merged**
