### PR TITLE
Upstream 8.0.1097

### PR DESCRIPTION
**Pull request by BlackIkeEagle**

### CODE REVIEW

**Comment by BlackIkeEagle** [comment]
the newest :terminal command is also not working now. I'm kind of out-of-my-league in this.

Can we do a request for people to contribute to vim-qt to help getting the `:terminal` command working and getting the channels setup correctly?

**Comment by equalsraf** [comment]
We seem to be missing event handling in the main loop for

- message queues
- timers

I dont have a working patch right now but the core of it seems to be

1. channel.c in FEAT_GUI_QT needs to be added, likely using a QSocketNotifier
2. in gui_qt.cpp in gu_mch_wait_for_char (or in our case qvimshell/vimwrapper.cpp), similar to gui_gtk_x11.c for FEAT_JOB_CHANNEL

**Comment by equalsraf** [comment]
I'm still missing some things but https://github.com/equalsraf/vim-qt/pull/12 seems to help with :term

**Comment by BlackIkeEagle** [comment]
nice, thanks @equalsraf

**Pull request merged**
